name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Install NVM and Node.js on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            source ~/.bashrc || exit
          

            node --version || exit
            npm --version || exit
          EOF

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            source ~/.bashrc || exit
          
            cd /home/ubuntu/ANOUT_OUT24_D03_AWS || exit
            git pull origin main || exit
            npm install || exit
            npm run build || exit
            pm2 restart api-nestjs || pm2 start dist/main.js --name "api-nestjs"
          EOF
