name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Conectar à instância EC2 e rodar o deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ubuntu/ANOUT_OUT24_D03_AWS || exit
            git pull origin main || exit
            npm install || exit
            npm run build || exit
            pm2 restart api-nestjs || pm2 start dist/main.js --name "api-nestjs"
          EOF
